### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by hughgallagher** [unic/SUGCON2015#1]
Hi, I downloaded the zip and opened in VS2015 in windows 10 and run the project but the references to Sitecore.Kernel and Sitecore.MVC are not set? So the project does not compile out of the box.

**Comment by kevinbrechbuehl** [comment]
You need to add both of the assemblies into the `lib` directory. See here: https://github.com/unic/SUGCON2015/tree/master/lib

Hope that helps. If not, feel free to reopen the issue again.
